services:
  idpfrontend:
    image: idpfrontend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"